-- MySQL Script generated by MySQL Workbench
-- Tue Nov 10 18:44:45 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema video
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema video
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `video` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `video` ;

-- -----------------------------------------------------
-- Table `video`.`film`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `video`.`film` ;

CREATE TABLE IF NOT EXISTS `video`.`film` (
  `film_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(128) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `release_year` YEAR NULL DEFAULT NULL,
  `length` SMALLINT UNSIGNED NULL DEFAULT NULL,
  `special_features` SET('Trailers', 'Commentaries', 'Deleted Scenes', 'Behind the Scenes') NULL DEFAULT NULL,
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`film_id`),
  INDEX `idx_title` (`title` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 2024
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `video`.`Village`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `video`.`Village` ;

CREATE TABLE IF NOT EXISTS `video`.`Village` (
  `idVillage` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `cp` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idVillage`),
  UNIQUE INDEX `idVillage_UNIQUE` (`idVillage` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `video`.`Show`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `video`.`Show` ;

CREATE TABLE IF NOT EXISTS `video`.`Show` (
  `idShow` INT NOT NULL AUTO_INCREMENT,
  `heure` DATETIME NULL DEFAULT NULL,
  `Village_idVillage` INT NOT NULL,
  `film_film_id` SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (`idShow`),
  UNIQUE INDEX `idShow_UNIQUE` (`idShow` ASC) VISIBLE,
  INDEX `fk_Show_Village1_idx` (`Village_idVillage` ASC) VISIBLE,
  INDEX `fk_Show_film1_idx` (`film_film_id` ASC) VISIBLE,
  CONSTRAINT `fk_Show_film1`
    FOREIGN KEY (`film_film_id`)
    REFERENCES `video`.`film` (`film_id`),
  CONSTRAINT `fk_Show_Village1`
    FOREIGN KEY (`Village_idVillage`)
    REFERENCES `video`.`Village` (`idVillage`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `video`.`Preference`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `video`.`Preference` ;

CREATE TABLE IF NOT EXISTS `video`.`Preference` (
  `idPreference` INT NOT NULL AUTO_INCREMENT,
  `vote` VARCHAR(45) NULL DEFAULT NULL,
  `Show_idShow` INT NOT NULL,
  `film_film_id` SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (`idPreference`),
  INDEX `fk_Preference_Show1_idx` (`Show_idShow` ASC) VISIBLE,
  INDEX `fk_Preference_film1_idx` (`film_film_id` ASC) VISIBLE,
  CONSTRAINT `fk_Preference_film1`
    FOREIGN KEY (`film_film_id`)
    REFERENCES `video`.`film` (`film_id`),
  CONSTRAINT `fk_Preference_Show1`
    FOREIGN KEY (`Show_idShow`)
    REFERENCES `video`.`Show` (`idShow`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `video`.`actor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `video`.`actor` ;

CREATE TABLE IF NOT EXISTS `video`.`actor` (
  `actor_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`actor_id`),
  INDEX `idx_actor_last_name` (`last_name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 201
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `video`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `video`.`category` ;

CREATE TABLE IF NOT EXISTS `video`.`category` (
  `category_id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(25) NOT NULL,
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 48
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `video`.`film_actor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `video`.`film_actor` ;

CREATE TABLE IF NOT EXISTS `video`.`film_actor` (
  `actor_id` SMALLINT UNSIGNED NOT NULL,
  `film_id` SMALLINT UNSIGNED NOT NULL,
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `film_film_id` SMALLINT UNSIGNED NULL,
  `actor_actor_id` SMALLINT UNSIGNED NULL,
  PRIMARY KEY (`actor_id`, `film_id`),
  INDEX `fk_film_actor_film1_idx` (`film_film_id` ASC) VISIBLE,
  INDEX `fk_film_actor_actor1_idx` (`actor_actor_id` ASC) VISIBLE,
  CONSTRAINT `fk_film_actor_film1`
    FOREIGN KEY (`film_film_id`)
    REFERENCES `video`.`film` (`film_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_film_actor_actor1`
    FOREIGN KEY (`actor_actor_id`)
    REFERENCES `video`.`actor` (`actor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `video`.`film_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `video`.`film_category` ;

CREATE TABLE IF NOT EXISTS `video`.`film_category` (
  `film_id` SMALLINT UNSIGNED NOT NULL,
  `category_id` TINYINT UNSIGNED NOT NULL,
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `film_film_id` SMALLINT UNSIGNED NULL,
  `category_category_id` TINYINT UNSIGNED NULL,
  PRIMARY KEY (`film_id`, `category_id`),
  INDEX `fk_film_category_film1_idx` (`film_film_id` ASC) VISIBLE,
  INDEX `fk_film_category_category1_idx` (`category_category_id` ASC) VISIBLE,
  CONSTRAINT `fk_film_category_film1`
    FOREIGN KEY (`film_film_id`)
    REFERENCES `video`.`film` (`film_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_film_category_category1`
    FOREIGN KEY (`category_category_id`)
    REFERENCES `video`.`category` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
